<a href="https://colab.research.google.com/github/bhomjan18/ML-Training/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Introduction to Numpy

What we will cover?
  * Creating single dimensional arrays👌
  * Multidimensional array👌
  * Randomly generated arrays👌
  * Element wise operations
  * Summarizing operations








###Single dimensional arrays

In [ ]:
import numpy as np

In [ ]:
# Create an array with all the elements to be zeros
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [ ]:
# Create an array with all the elements to be zeros
np.ones(5)

array([1., 1., 1., 1., 1.])

In [ ]:
# Create an array of the size 10 with all elements 3
np.full(10, 3)

array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [ ]:
np.array([1, 2, 3, 4, 5])

array([1, 2, 3, 4, 5])

In [ ]:
np.arange(3, 10)

array([3, 4, 5, 6, 7, 8, 9])

In [ ]:
# Create an array with evenly sapced numbers within a specifid range
np.linspace(0, 100, 11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

### Multidimensional arrays

In [ ]:
np.zeros([3,5])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
np.ones([3,3])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
a = np.array([[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]])


In [ ]:
a[0,1] = 20
print(a)

[[ 1 20  3]
 [ 4  5  6]
 [ 7  8  9]]


In [ ]:
a[2] = [1, 1, 1]
print(a)

[[ 1 20  3]
 [ 4  5  6]
 [ 1  1  1]]


In [ ]:
a[:, 2] = [2, 2, 2]
a

array([[ 1, 20,  2],
       [ 4,  5,  2],
       [ 1,  1,  2]])

In [ ]:
# Create an multidimensioanal array with all elements 10
np.full((3, 3),10)

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

###Randomly generated arrays
* Numpy can create arrays filled with random numbers
* To ensure the reproducibility, you can seta sed using ```np.random.seed()```.It will generate the exact same random numbers for each executions.
* If you remove or change the seed values, the sequence of random numbers will be changed.

In [ ]:
np.random.rand(5)

array([0.39910062, 0.39156415, 0.8217634 , 0.32367315, 0.87711627])

In [ ]:
np.random.seed(80)
np.random.rand(5)

array([0.52191572, 0.69940637, 0.26986897, 0.67448187, 0.90807208])

In [ ]:
np.random.randn(5, 2)

array([[ 0.54794733, -0.52658091],
       [ 1.17223107, -0.48103231],
       [-1.00073842, -1.18248113],
       [-0.43654296, -2.64063134],
       [ 0.01571955,  0.02997534]])

In [ ]:
np.random.randint(low=0, high=100, size=(5, 2))

array([[24,  1],
       [17, 54],
       [16, 41],
       [20, 31],
       [24, 67]])

###Element Wise operation on entire arrays element by element

In [2]:
import numpy as np
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [3]:
b = (10 + (a*2))
b

array([10, 12, 14, 16, 18])

In [4]:
# Comparison operation
a


array([0, 1, 2, 3, 4])

In [5]:
a >= 2

array([False, False,  True,  True,  True])

In [6]:
a > b

array([False, False, False, False, False])

In [7]:
# Summarizing  of the data
# Numpy provides function for summerizing array data
a


array([0, 1, 2, 3, 4])

In [8]:
a.std()

1.4142135623730951

In [9]:
# Min, Max and Sum
a.sum()

10

In [10]:
a.min()

0

In [11]:
a.max()

4